/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DBSProject;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.sql.SQLException;

/**
 *
 * @author Admin
 */
public class AdminVerification extends javax.swing.JFrame {

    /**
     * Creates new form AdminVerification
     */
    public AdminVerification() {
        initComponents();
        setSize(467,400);
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginpanle = new javax.swing.JPanel();
        avpanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        loginpanel = new javax.swing.JPanel();
        username = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        usernametf = new javax.swing.JTextField();
        passwordtf = new javax.swing.JPasswordField();
        usernameerror = new javax.swing.JLabel();
        passworderror = new javax.swing.JLabel();
        loginbtn = new javax.swing.JButton();
        cancel = new javax.swing.JButton();

        loginpanle.setBackground(new java.awt.Color(255, 204, 204));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setResizable(false);
        setSize(new java.awt.Dimension(450, 450));
        getContentPane().setLayout(null);

        avpanel.setBackground(new java.awt.Color(51, 131, 228));
        avpanel.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Login");
        avpanel.add(jLabel1);
        jLabel1.setBounds(170, 0, 110, 70);

        getContentPane().add(avpanel);
        avpanel.setBounds(0, 0, 450, 70);

        loginpanel.setBackground(new java.awt.Color(184, 167, 135));
        loginpanel.setLayout(null);

        username.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        username.setText("Username:");
        loginpanel.add(username);
        username.setBounds(70, 60, 80, 30);

        password.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        password.setText(" Password:");
        loginpanel.add(password);
        password.setBounds(70, 130, 80, 30);
        loginpanel.add(usernametf);
        usernametf.setBounds(150, 60, 220, 30);
        loginpanel.add(passwordtf);
        passwordtf.setBounds(150, 130, 220, 30);

        usernameerror.setForeground(new java.awt.Color(255, 0, 0));
        loginpanel.add(usernameerror);
        usernameerror.setBounds(150, 90, 220, 20);
        usernameerror.setVisible(false);

        passworderror.setForeground(new java.awt.Color(255, 0, 0));
        loginpanel.add(passworderror);
        passworderror.setBounds(150, 160, 220, 20);
        passworderror.setVisible(false);

        loginbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        loginbtn.setText("Login->");
        loginbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbtnActionPerformed(evt);
            }
        });
        loginpanel.add(loginbtn);
        loginbtn.setBounds(90, 190, 110, 30);

        cancel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cancel.setText("Cancel");
        cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        loginpanel.add(cancel);
        cancel.setBounds(250, 190, 110, 30);

        getContentPane().add(loginpanel);
        loginpanel.setBounds(0, 70, 450, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbtnActionPerformed
        
        try{
            String Admin="";
            String Password="";
            Connection con2 = new DBConnection().getConnection();
            Statement s=con2.createStatement();
            ResultSet rs = s.executeQuery("select * from username_password");
            while(rs.next())
            {
                Admin=rs.getString(1);
                Password=rs.getString(2);
            }
            con2.close();
            char[] psw = passwordtf.getPassword();
            String pstring=new String(psw);
            if(usernametf.getText().equals(Admin) && pstring.equals(Password))
            {
                usernameerror.setVisible(false);
                passworderror.setVisible(false);
                new AdminFrame().setVisible(true);
                this.dispose();
            }
            else if(usernametf.getText().equals("") && pstring.equals(""))
            {
                usernameerror.setText("Please enter username!");
                passworderror.setText("Please enter password!");
                usernameerror.setVisible(true);
                passworderror.setVisible(true);
            }
            else if(usernametf.getText().equals("") && pstring.equals(password))
            {
                passworderror.setVisible(false);
                usernameerror.setText("Please enter username!");
                usernameerror.setVisible(true);
            }
            
            else if(pstring.equals("") && usernametf.getText().equals(Admin))
            {
                usernameerror.setVisible(false);
                passworderror.setText("Please enter password!");
                passworderror.setVisible(true);
            }
            
            else if(usernametf.getText().equals(Admin) && pstring!=Password)
            {
                passworderror.setText("Please enter correct password!");
                passworderror.setVisible(true);
                usernameerror.setVisible(false);
            }
            
            else if(usernametf.getText()!=Admin && pstring.equals(Password))
            {
                usernameerror.setText("Please enter correct username!");
                usernameerror.setVisible(true);
                passworderror.setVisible(false);
            }
            
            else if(usernametf.getText()!=Admin && pstring!=Password)
            {
                usernameerror.setText("Please enter correct username!");
                passworderror.setText("Please enter correct password!");
                usernameerror.setVisible(true);
                passworderror.setVisible(true);
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }
       
    }//GEN-LAST:event_loginbtnActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        
        new MainFrame().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_cancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminVerification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminVerification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminVerification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminVerification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminVerification().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel avpanel;
    private javax.swing.JButton cancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton loginbtn;
    private javax.swing.JPanel loginpanel;
    private javax.swing.JPanel loginpanle;
    private javax.swing.JLabel password;
    private javax.swing.JLabel passworderror;
    private javax.swing.JPasswordField passwordtf;
    private javax.swing.JLabel username;
    private javax.swing.JLabel usernameerror;
    private javax.swing.JTextField usernametf;
    // End of variables declaration//GEN-END:variables
}
