/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DBSProject;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import java.sql.SQLException;

/**
 *
 * @author Admin
 */
public class Guest extends javax.swing.JFrame {

    Date date=new Date();
    SimpleDateFormat dateformat=new SimpleDateFormat("dd/MMMM/YYYY");    
    /**
     * Creates new form Guest
     */
    public Guest() {
        initComponents();
        setSize(1200,700);
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        datacollectingpanel = new javax.swing.JPanel();
        stdrollno = new javax.swing.JLabel();
        g1name = new javax.swing.JLabel();
        g2name = new javax.swing.JLabel();
        g1rollno = new javax.swing.JLabel();
        g1rollnotf = new javax.swing.JTextField();
        condition1 = new javax.swing.JLabel();
        g2rollno = new javax.swing.JLabel();
        g2rollnotf = new javax.swing.JTextField();
        condition2 = new javax.swing.JLabel();
        allow = new javax.swing.JButton();
        stdrollnolabel = new javax.swing.JLabel();
        g1details = new javax.swing.JLabel();
        g1contact = new javax.swing.JLabel();
        g1contacttf = new javax.swing.JTextField();
        g2details = new javax.swing.JLabel();
        g2nametf = new javax.swing.JTextField();
        g2contact = new javax.swing.JLabel();
        g2contacttf = new javax.swing.JTextField();
        clear = new javax.swing.JButton();
        g1nametf = new javax.swing.JTextField();
        rollnotf = new javax.swing.JTextField();
        back = new javax.swing.JLabel();
        guesttablepanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        scrollpane = new javax.swing.JScrollPane();
        guesttable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        guestmenulabel = new javax.swing.JPanel();
        guestdatalabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(200, 100, 600, 600));
        getContentPane().setLayout(null);

        datacollectingpanel.setBackground(new java.awt.Color(248, 245, 241));
        datacollectingpanel.setLayout(null);

        stdrollno.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        stdrollno.setText("Roll No");
        datacollectingpanel.add(stdrollno);
        stdrollno.setBounds(120, 80, 50, 30);

        g1name.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        g1name.setText("Name");
        datacollectingpanel.add(g1name);
        g1name.setBounds(130, 230, 50, 30);

        g2name.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        g2name.setText("Name");
        datacollectingpanel.add(g2name);
        g2name.setBounds(130, 430, 50, 30);

        g1rollno.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        g1rollno.setText("Roll No");
        datacollectingpanel.add(g1rollno);
        g1rollno.setBounds(120, 180, 60, 30);

        g1rollnotf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                g1rollnotfKeyPressed(evt);
            }
        });
        datacollectingpanel.add(g1rollnotf);
        g1rollnotf.setBounds(180, 180, 240, 30);

        condition1.setText("( If he/she blongs to this university )");
        datacollectingpanel.add(condition1);
        condition1.setBounds(180, 150, 200, 30);

        g2rollno.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        g2rollno.setText("  Roll No");
        datacollectingpanel.add(g2rollno);
        g2rollno.setBounds(110, 380, 70, 30);

        g2rollnotf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                g2rollnotfKeyPressed(evt);
            }
        });
        datacollectingpanel.add(g2rollnotf);
        g2rollnotf.setBounds(180, 380, 240, 30);

        condition2.setText("( If he/she belongs to this university )");
        datacollectingpanel.add(condition2);
        condition2.setBounds(180, 350, 220, 30);

        allow.setBackground(new java.awt.Color(153, 204, 255));
        allow.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        allow.setText("Allow");
        allow.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        allow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allowActionPerformed(evt);
            }
        });
        datacollectingpanel.add(allow);
        allow.setBounds(110, 560, 130, 30);

        stdrollnolabel.setText("( Roll No of student of this hostel )");
        datacollectingpanel.add(stdrollnolabel);
        stdrollnolabel.setBounds(180, 50, 210, 30);

        g1details.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        g1details.setText("( Details of first Guest )");
        datacollectingpanel.add(g1details);
        g1details.setBounds(120, 120, 160, 30);

        g1contact.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        g1contact.setText("    Contact No");
        datacollectingpanel.add(g1contact);
        g1contact.setBounds(80, 280, 100, 30);

        g1contacttf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                g1contacttfKeyPressed(evt);
            }
        });
        datacollectingpanel.add(g1contacttf);
        g1contacttf.setBounds(180, 280, 240, 30);

        g2details.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        g2details.setText("( Details of second Guest )");
        datacollectingpanel.add(g2details);
        g2details.setBounds(120, 320, 170, 30);

        g2nametf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                g2nametfKeyPressed(evt);
            }
        });
        datacollectingpanel.add(g2nametf);
        g2nametf.setBounds(180, 430, 240, 30);

        g2contact.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        g2contact.setText(" Contact No");
        datacollectingpanel.add(g2contact);
        g2contact.setBounds(90, 480, 90, 30);

        g2contacttf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                g2contacttfKeyPressed(evt);
            }
        });
        datacollectingpanel.add(g2contacttf);
        g2contacttf.setBounds(180, 480, 240, 30);

        clear.setBackground(new java.awt.Color(153, 204, 255));
        clear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        clear.setText("Clear");
        clear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        datacollectingpanel.add(clear);
        clear.setBounds(280, 560, 130, 30);

        g1nametf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                g1nametfKeyPressed(evt);
            }
        });
        datacollectingpanel.add(g1nametf);
        g1nametf.setBounds(180, 230, 240, 30);

        rollnotf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rollnotfActionPerformed(evt);
            }
        });
        rollnotf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rollnotfKeyPressed(evt);
            }
        });
        datacollectingpanel.add(rollnotf);
        rollnotf.setBounds(180, 80, 240, 30);

        back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        datacollectingpanel.add(back);
        back.setBounds(10, 10, 25, 30);

        getContentPane().add(datacollectingpanel);
        datacollectingpanel.setBounds(0, 0, 530, 700);

        guesttablepanel.setBackground(new java.awt.Color(248, 245, 241));
        guesttablepanel.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(243, 200, 243));
        jPanel1.setLayout(null);

        guesttable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Std Roll No", "Guest 1 Roll No", "Guest 1 Name", "Guest 1 Contact", "Guest 2 Roll No", "Guest 2 Name", "Guest 2 Contact", "Entry Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        guesttable.setShowHorizontalLines(true);
        guesttable.setShowVerticalLines(true);
        guesttable.getTableHeader().setReorderingAllowed(false);
        scrollpane.setViewportView(guesttable);

        jPanel1.add(scrollpane);
        scrollpane.setBounds(0, 0, 660, 370);

        guesttablepanel.add(jPanel1);
        jPanel1.setBounds(0, 0, 660, 370);

        jButton1.setBackground(new java.awt.Color(153, 204, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("Show Table");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        guesttablepanel.add(jButton1);
        jButton1.setBounds(250, 490, 180, 40);

        getContentPane().add(guesttablepanel);
        guesttablepanel.setBounds(530, 50, 660, 650);

        guestmenulabel.setBackground(new java.awt.Color(124, 141, 131));
        guestmenulabel.setLayout(null);

        guestdatalabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        guestdatalabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guestdatalabel.setText("Guest Data");
        guestmenulabel.add(guestdatalabel);
        guestdatalabel.setBounds(250, 0, 190, 50);

        getContentPane().add(guestmenulabel);
        guestmenulabel.setBounds(530, 0, 660, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void allowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allowActionPerformed
       
        String stdrollno=rollnotf.getText();
        String g1rollno=g1rollnotf.getText();
        String g1name=g1nametf.getText();
        double g1contact=Double.parseDouble(g1contacttf.getText());
        String g2rollno=g2rollnotf.getText();
        String g2name=g2nametf.getText();
        double g2contact=Double.parseDouble(g2contacttf.getText());
        String dt=dateformat.format(date);
        
        try{
            Connection con2=new DBConnection().getConnection();
            Statement s=con2.createStatement();
            s.executeQuery("insert into guest_data(std_roll_no, guest_1_roll_no, guest_1_name, guest_1_contact_no, guest_2_roll_no, guest_2_name, guest_2_contact_no, entry_date) values ('"+
                    stdrollno+"','"+g1rollno+"','"+g1name+"','"+g1contact+"','"+g2rollno+"','"+g2name+"','"+g2contact+"','"+dt+"')");
            s.executeQuery("commit");
            con2.close();
            JOptionPane.showMessageDialog(null, "Data Saved");
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }
        
    }//GEN-LAST:event_allowActionPerformed

    private void rollnotfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rollnotfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rollnotfActionPerformed

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        
        this.dispose();
        new AdminFrame().setVisible(true);
        
    }//GEN-LAST:event_backMouseClicked

    private void rollnotfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rollnotfKeyPressed
        
            char ch=evt.getKeyChar();
            
           if(Character.isLetter(ch) || Character.isDigit(ch) || Character.isISOControl(ch))
           {
               rollnotf.setEditable(true);
           }
           else
           {
               rollnotf.setEditable(false);
           }
        
    }//GEN-LAST:event_rollnotfKeyPressed

    private void g1rollnotfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_g1rollnotfKeyPressed
        
            char ch=evt.getKeyChar();
            
           if(Character.isLetter(ch) || Character.isDigit(ch) || Character.isISOControl(ch))
           {
               g1rollnotf.setEditable(true);
           }
           else
           {
               g1rollnotf.setEditable(false);
           }
        
    }//GEN-LAST:event_g1rollnotfKeyPressed

    private void g2rollnotfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_g2rollnotfKeyPressed
        
            char ch=evt.getKeyChar();
            
           if(Character.isLetter(ch) || Character.isDigit(ch) || Character.isISOControl(ch))
           {
               g2rollnotf.setEditable(true);
           }
           else
           {
               g2rollnotf.setEditable(false);
           }
        
    }//GEN-LAST:event_g2rollnotfKeyPressed

    private void g1nametfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_g1nametfKeyPressed
        
        char ch=evt.getKeyChar();
        
        if(Character.isLetter(ch) || Character.isWhitespace(ch) || Character.isISOControl(ch))
        {
            g1nametf.setEditable(true);
        }
        else
        {
            g1nametf.setEditable(false);
        }
        
    }//GEN-LAST:event_g1nametfKeyPressed

    private void g2nametfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_g2nametfKeyPressed
        
        char ch=evt.getKeyChar();
        
        if(Character.isLetter(ch) || Character.isWhitespace(ch) || Character.isISOControl(ch))
        {
            g2nametf.setEditable(true);
        }
        else
        {
            g2nametf.setEditable(false);
        }
        
    }//GEN-LAST:event_g2nametfKeyPressed

    private void g1contacttfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_g1contacttfKeyPressed
        
            char ch=evt.getKeyChar();
           
           if(Character.isDigit(ch) || Character.isWhitespace(ch) || Character.isISOControl(ch))
           {
               g1contacttf.setEditable(true);
           }
           else
           {
               g1contacttf.setEditable(false);
           }
        
    }//GEN-LAST:event_g1contacttfKeyPressed

    private void g2contacttfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_g2contacttfKeyPressed
        
            char ch=evt.getKeyChar();
           
           if(Character.isDigit(ch) || Character.isWhitespace(ch) || Character.isISOControl(ch))
           {
               g2contacttf.setEditable(true);
           }
           else
           {
               g2contacttf.setEditable(false);
           }
        
    }//GEN-LAST:event_g2contacttfKeyPressed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed

        rollnotf.setText(null);
        g1rollnotf.setText(null);
        g1nametf.setText(null);
        g1contacttf.setText(null);
        g2rollnotf.setText(null);
        g2nametf.setText(null);
        g2contacttf.setText(null);

    }//GEN-LAST:event_clearActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        boolean check=true;

        javax.swing.table.DefaultTableModel model;

        guesttable.setModel(new javax.swing.table.DefaultTableModel(null,new String[] {"Std Roll No", "Guest 1 Roll No", "Guest 1 Name","Guest 1 Contact", "Guest 2 Roll No", "Guest 2 Name", "Guest 2 Contact","Entry Date"}));
        try{
            Connection con=new DBConnection().getConnection();
            Statement s=con.createStatement();
            ResultSet rs=s.executeQuery("select * from guest_data");
            while(rs.next())
            {
                check=false;
                String stdrollno=rs.getString(1);
                String g1rollno=rs.getString(2);
                String g1name=rs.getString(3);
                String g1contact=String.valueOf(rs.getLong(4));
                String g2rollno=rs.getString(5);
                String g2name=rs.getString(6);
                String g2contact=String.valueOf(rs.getLong(7));
                String date=String.valueOf(rs.getDate(8));

                String[] data={stdrollno,g1rollno,g1name,g1contact,g2rollno,g2name,g2contact,date};
                model=(javax.swing.table.DefaultTableModel) guesttable.getModel();
                model.addRow(data);
            }

            if(check)
            {
                JOptionPane.showMessageDialog(null, "Table is empty!");
            }

            con.close();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Guest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Guest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Guest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Guest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Guest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton allow;
    private javax.swing.JLabel back;
    private javax.swing.JButton clear;
    private javax.swing.JLabel condition1;
    private javax.swing.JLabel condition2;
    private javax.swing.JPanel datacollectingpanel;
    private javax.swing.JLabel g1contact;
    private javax.swing.JTextField g1contacttf;
    private javax.swing.JLabel g1details;
    private javax.swing.JLabel g1name;
    private javax.swing.JTextField g1nametf;
    private javax.swing.JLabel g1rollno;
    private javax.swing.JTextField g1rollnotf;
    private javax.swing.JLabel g2contact;
    private javax.swing.JTextField g2contacttf;
    private javax.swing.JLabel g2details;
    private javax.swing.JLabel g2name;
    private javax.swing.JTextField g2nametf;
    private javax.swing.JLabel g2rollno;
    private javax.swing.JTextField g2rollnotf;
    private javax.swing.JLabel guestdatalabel;
    private javax.swing.JPanel guestmenulabel;
    private javax.swing.JTable guesttable;
    private javax.swing.JPanel guesttablepanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField rollnotf;
    private javax.swing.JScrollPane scrollpane;
    private javax.swing.JLabel stdrollno;
    private javax.swing.JLabel stdrollnolabel;
    // End of variables declaration//GEN-END:variables
}
