/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DBSProject;

/**
 *
 * @author Admin
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        setSize(1200,700);
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu1 = new java.awt.PopupMenu();
        mainframepanel = new javax.swing.JPanel();
        adminaccess = new javax.swing.JButton();
        studentaccess = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        mainframetitle = new javax.swing.JLabel();

        popupMenu1.setLabel("popupMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setResizable(false);
        setSize(new java.awt.Dimension(1200, 700));
        getContentPane().setLayout(null);

        mainframepanel.setBackground(new java.awt.Color(248, 245, 241));
        mainframepanel.setLayout(null);

        adminaccess.setBackground(new java.awt.Color(153, 204, 255));
        adminaccess.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        adminaccess.setText("Admin");
        adminaccess.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        adminaccess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminaccessActionPerformed(evt);
            }
        });
        mainframepanel.add(adminaccess);
        adminaccess.setBounds(920, 300, 150, 30);

        studentaccess.setBackground(new java.awt.Color(153, 204, 255));
        studentaccess.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        studentaccess.setText("Student");
        studentaccess.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        studentaccess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentaccessActionPerformed(evt);
            }
        });
        mainframepanel.add(studentaccess);
        studentaccess.setBounds(920, 400, 150, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MainFrame.jpg"))); // NOI18N
        mainframepanel.add(jLabel1);
        jLabel1.setBounds(40, 150, 750, 470);

        mainframetitle.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        mainframetitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainframetitle.setText("Hostel Management System");
        mainframepanel.add(mainframetitle);
        mainframetitle.setBounds(150, 20, 860, 80);

        getContentPane().add(mainframepanel);
        mainframepanel.setBounds(0, 0, 1190, 680);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void studentaccessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentaccessActionPerformed
        
        new UserFrame().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_studentaccessActionPerformed

    private void adminaccessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminaccessActionPerformed
        
        new AdminVerification().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_adminaccessActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminaccess;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel mainframepanel;
    private javax.swing.JLabel mainframetitle;
    private java.awt.PopupMenu popupMenu1;
    private javax.swing.JButton studentaccess;
    // End of variables declaration//GEN-END:variables
}
