/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DBSProject;
import java.awt.Color;
import java.sql.SQLException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class StdDataCollectionNonAC extends javax.swing.JFrame {

    Date date=new Date();
    SimpleDateFormat dateformat=new SimpleDateFormat("dd/MMMM/YYYY");
    String Rolno;
    /**
     * Creates new form StdDataCollectionNonAC
     */
    public StdDataCollectionNonAC() {
        initComponents();
        setSize(1200,700);
        setLocationRelativeTo(null);
        setResizable(false);
    }
    
    public void setRollNo(String rollno){
        this.Rolno = rollno;
    }
    
    public String getRollNo(){
        return Rolno;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        rollnotf = new javax.swing.JTextField();
        rollno = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        nametf = new javax.swing.JTextField();
        fnametf = new javax.swing.JTextField();
        fname = new javax.swing.JLabel();
        contact = new javax.swing.JLabel();
        contacttf = new javax.swing.JTextField();
        bg = new javax.swing.JComboBox<>();
        bloodgroup = new javax.swing.JLabel();
        country = new javax.swing.JLabel();
        countrytf = new javax.swing.JTextField();
        provincetf = new javax.swing.JTextField();
        province = new javax.swing.JLabel();
        district = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        addresstf = new javax.swing.JTextField();
        districttf = new javax.swing.JTextField();
        clear = new javax.swing.JButton();
        submit = new javax.swing.JButton();
        emergcontacttf = new javax.swing.JTextField();
        emailtf = new javax.swing.JTextField();
        email = new javax.swing.JLabel();
        emergcontact = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(10, 10, 25, 30);

        jPanel1.setBackground(new java.awt.Color(248, 245, 241));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("( i.e 19SW01 )");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(180, 20, 90, 30);

        rollnotf.setForeground(new java.awt.Color(153, 153, 153));
        rollnotf.setText("Roll No");
        rollnotf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                rollnotfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                rollnotfFocusLost(evt);
            }
        });
        rollnotf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rollnotfKeyPressed(evt);
            }
        });
        jPanel1.add(rollnotf);
        rollnotf.setBounds(180, 50, 230, 30);

        rollno.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rollno.setText(" Roll No");
        jPanel1.add(rollno);
        rollno.setBounds(120, 50, 60, 30);

        name.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        name.setText(" Name");
        jPanel1.add(name);
        name.setBounds(130, 100, 50, 30);

        nametf.setForeground(new java.awt.Color(153, 153, 153));
        nametf.setText("Name");
        nametf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nametfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nametfFocusLost(evt);
            }
        });
        nametf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nametfKeyPressed(evt);
            }
        });
        jPanel1.add(nametf);
        nametf.setBounds(180, 100, 230, 30);

        fnametf.setForeground(new java.awt.Color(153, 153, 153));
        fnametf.setText("Father Name");
        fnametf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fnametfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fnametfFocusLost(evt);
            }
        });
        fnametf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fnametfKeyPressed(evt);
            }
        });
        jPanel1.add(fnametf);
        fnametf.setBounds(180, 150, 230, 30);

        fname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fname.setText("  Father's Name");
        jPanel1.add(fname);
        fname.setBounds(70, 150, 110, 30);

        contact.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        contact.setText("Contact");
        jPanel1.add(contact);
        contact.setBounds(120, 200, 60, 30);

        contacttf.setForeground(new java.awt.Color(153, 153, 153));
        contacttf.setText("03*********");
        contacttf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                contacttfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                contacttfFocusLost(evt);
            }
        });
        contacttf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contacttfActionPerformed(evt);
            }
        });
        contacttf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                contacttfKeyPressed(evt);
            }
        });
        jPanel1.add(contacttf);
        contacttf.setBounds(180, 200, 230, 30);

        bg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-" }));
        jPanel1.add(bg);
        bg.setBounds(180, 250, 59, 22);

        bloodgroup.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bloodgroup.setText("Blood Group");
        jPanel1.add(bloodgroup);
        bloodgroup.setBounds(90, 250, 90, 20);

        country.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        country.setText("Country");
        jPanel1.add(country);
        country.setBounds(120, 290, 60, 30);

        countrytf.setForeground(new java.awt.Color(153, 153, 153));
        countrytf.setText("Country Name");
        countrytf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                countrytfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                countrytfFocusLost(evt);
            }
        });
        countrytf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                countrytfKeyPressed(evt);
            }
        });
        jPanel1.add(countrytf);
        countrytf.setBounds(180, 290, 230, 30);

        provincetf.setForeground(new java.awt.Color(153, 153, 153));
        provincetf.setText("Province Name");
        provincetf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                provincetfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                provincetfFocusLost(evt);
            }
        });
        provincetf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                provincetfKeyPressed(evt);
            }
        });
        jPanel1.add(provincetf);
        provincetf.setBounds(180, 340, 230, 30);

        province.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        province.setText(" Province");
        jPanel1.add(province);
        province.setBounds(110, 340, 70, 30);

        district.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        district.setText(" District");
        jPanel1.add(district);
        district.setBounds(120, 390, 60, 30);

        address.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        address.setText("  Address");
        jPanel1.add(address);
        address.setBounds(110, 440, 70, 30);

        addresstf.setForeground(new java.awt.Color(153, 153, 153));
        addresstf.setText("Address");
        addresstf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                addresstfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                addresstfFocusLost(evt);
            }
        });
        addresstf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                addresstfKeyPressed(evt);
            }
        });
        jPanel1.add(addresstf);
        addresstf.setBounds(180, 440, 230, 30);

        districttf.setForeground(new java.awt.Color(153, 153, 153));
        districttf.setText("District Name");
        districttf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                districttfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                districttfFocusLost(evt);
            }
        });
        districttf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                districttfKeyPressed(evt);
            }
        });
        jPanel1.add(districttf);
        districttf.setBounds(180, 390, 230, 30);

        clear.setBackground(new java.awt.Color(153, 204, 255));
        clear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        clear.setText("Clear");
        clear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel1.add(clear);
        clear.setBounds(280, 600, 100, 30);

        submit.setBackground(new java.awt.Color(153, 204, 255));
        submit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        submit.setText("Submit");
        submit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        jPanel1.add(submit);
        submit.setBounds(130, 600, 100, 30);

        emergcontacttf.setForeground(new java.awt.Color(153, 153, 153));
        emergcontacttf.setText("03*********");
        emergcontacttf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emergcontacttfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emergcontacttfFocusLost(evt);
            }
        });
        emergcontacttf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                emergcontacttfKeyPressed(evt);
            }
        });
        jPanel1.add(emergcontacttf);
        emergcontacttf.setBounds(180, 540, 230, 30);

        emailtf.setForeground(new java.awt.Color(153, 153, 153));
        emailtf.setText("Email");
        emailtf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailtfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailtfFocusLost(evt);
            }
        });
        jPanel1.add(emailtf);
        emailtf.setBounds(180, 490, 230, 30);

        email.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        email.setText(" Email");
        jPanel1.add(email);
        email.setBounds(130, 490, 50, 30);

        emergcontact.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        emergcontact.setText("Emergency Contact");
        jPanel1.add(emergcontact);
        emergcontact.setBounds(40, 540, 130, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Non AC Room.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(610, 130, 500, 430);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1210, 740);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        
        rollnotf.setText(null);
        nametf.setText(null);
        fnametf.setText(null);
        contacttf.setText(null);
        countrytf.setText(null);
        provincetf.setText(null);
        districttf.setText(null);
        addresstf.setText(null);
        emailtf.setText(null);
        emergcontacttf.setText(null);
        
    }//GEN-LAST:event_clearActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed

        if(rollnotf.getText().isEmpty() || nametf.getText().isEmpty() || fnametf.getText().isEmpty() || contacttf.getText().isEmpty() || countrytf.getText().isEmpty() || provincetf.getText().isEmpty() || districttf.getText().isEmpty() || addresstf.getText().isEmpty() || emailtf.getText().isEmpty() || emergcontacttf.getText().isEmpty() )
        {
            JOptionPane.showMessageDialog(null, "Something is wrong while getting data!", null, JOptionPane.ERROR_MESSAGE);
        }
        
        else if(rollnotf.getText().equals("Roll No") || nametf.getText().equals("Name") || fnametf.getText().equals("Father Name") || contacttf.getText().equals("03*********") || countrytf.getText().equals("Country Name") || provincetf.getText().equals("Province Name") || districttf.getText().equals("District Name") || addresstf.getText().equals("Address") || emailtf.getText().equals("Email") || emergcontacttf.getText().equals("03*********"))
        {
            JOptionPane.showMessageDialog(null, "Something is wrong while getting data!", null, JOptionPane.ERROR_MESSAGE);
        }
        
        else if(rollnotf.getText().equals(getRollNo()))
        {
            boolean check1 = false, check2 = false, check3 = false, check4 = false, check5 = false;
            String roomno=null;
            int rooms = 0;
            String rollno = rollnotf.getText();
           try{
               Connection con = new DBConnection().getConnection();
               Statement s = con.createStatement();
               
               ResultSet rs3 = s.executeQuery("select roll_no from hostel_data_ac");
               while(rs3.next())
               {
                   if(rs3.getString(1).equals(rollno))
                   {
                       check3 = true;
                       break;
                   }
               }
               
               ResultSet rs4 = s.executeQuery("select roll_no from hostel_data_non_ac");
               while(rs4.next())
               {
                   if(rs4.getString(1).equals(rollno))
                   {
                       check4 = true;
                       break;
                   }
               }
               
               if(emailtf.getText().endsWith("@gmail.com") || emailtf.getText().endsWith("@email.com"))
               {
                    if(check3)
                    {
                        JOptionPane.showMessageDialog(null, "This roll no is already allocated a AC room");
                    }

                    else if (check4)
                    {
                        JOptionPane.showMessageDialog(null, "This roll no is already allocated a Non AC room");
                    }

                    else
                    {
                         ResultSet rs = s.executeQuery("select non_ac_rooms from rooms");
                         while(rs.next())
                         {
                             rooms = rs.getInt(1);
                         }
                         if(rooms==0)
                         {
                             JOptionPane.showMessageDialog(null, "Non AC room is not available!", null, JOptionPane.ERROR_MESSAGE);
                         }

                         else 
                         {
                              ResultSet rs2 = s.executeQuery("select * from non_ac_rooms_allocation order by room_no asc");
                              while(rs2.next())
                              {
                                  String str1 = rs2.getString("std_1_roll_no");
                                  String str2 = rs2.getString("std_2_roll_no");
                                  if(str1.equals(" "))
                                  {
                                      check1 = true;
                                      roomno = rs2.getString(1);
                                      break;
                                  }

                                  else if(str2.equals(" "))
                                  {
                                      check2 = true;
                                      roomno = rs2.getString(1);
                                      break;
                                  }

                                  else
                                  {
                                      check5 = true;
                                  }
                              }

                              if(check1)
                              {
                                  String Name=nametf.getText();
                                  String Fname=fnametf.getText();
                                  double Contact=Double.parseDouble(contacttf.getText());
                                  String Blood_group=(String)bg.getSelectedItem();
                                  String Country=countrytf.getText();
                                  String Province=provincetf.getText();
                                  String District=districttf.getText();
                                  String Address=addresstf.getText();
                                  String Email=emailtf.getText();
                                  double Emerg_contact=Double.parseDouble(emergcontacttf.getText());
                                  s.executeQuery("insert into hostel_data_non_ac(roll_no, name, f_name, contact_no, blood_group, country, province, district, address, email, emerg_contact, room_allow_date) values('"+rollno+"','"+Name+"','"+Fname+"','"+Contact+"','"+Blood_group+"','"+Country+"','"+Province+"','"+District+"','"+Address+"','"+Email+"','"+Emerg_contact+"','"+dateformat.format(date)+"')");
                                  s.executeQuery("update non_ac_rooms_allocation set std_1_roll_no = '"+rollno+"' where room_no = '"+roomno+"'");
                                  s.executeQuery("commit");
                                  JOptionPane.showMessageDialog(null, "Your room number is "+roomno);
                              }

                              else if (check2)
                              {
                                  String Name=nametf.getText();
                                  String Fname=fnametf.getText();
                                  double Contact=Double.parseDouble(contacttf.getText());
                                  String Blood_group=(String)bg.getSelectedItem();
                                  String Country=countrytf.getText();
                                  String Province=provincetf.getText();
                                  String District=districttf.getText();
                                  String Address=addresstf.getText();
                                  String Email=emailtf.getText();
                                  double Emerg_contact=Double.parseDouble(emergcontacttf.getText());
                                  s.executeQuery("insert into hostel_data_non_ac(roll_no, name, f_name, contact_no, blood_group, country, province, district, address, email, emerg_contact, room_allow_date) values('"+rollno+"','"+Name+"','"+Fname+"','"+Contact+"','"+Blood_group+"','"+Country+"','"+Province+"','"+District+"','"+Address+"','"+Email+"','"+Emerg_contact+"','"+dateformat.format(date)+"')");
                                  s.executeQuery("update non_ac_rooms_allocation set std_2_roll_no = '"+rollno+"' where room_no = '"+roomno+"'");
                                  s.executeQuery("commit");
                                  JOptionPane.showMessageDialog(null, "Your room number is "+roomno);
                              }

                              else if(check5)
                              {
                                  JOptionPane.showMessageDialog(null, "Non AC room is not available!", null, JOptionPane.ERROR_MESSAGE);
                              }
                         }

                    }
               }
               
               else
               {
                   JOptionPane.showMessageDialog(null, "Pattern of the email is not correct!", null, JOptionPane.ERROR_MESSAGE);
               }
               con.close();
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null,e);
            }
        }
        
        else
        {
            JOptionPane.showMessageDialog(null, "Enter correct Roll No!", null, JOptionPane.ERROR_MESSAGE);
        }
      
    }//GEN-LAST:event_submitActionPerformed

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked

        UserFrame obj = new UserFrame();
        obj.setRollNo(getRollNo());
        obj.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_backMouseClicked

    private void nametfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nametfKeyPressed
        
        char ch=evt.getKeyChar();
        
        if(Character.isLetter(ch) || Character.isWhitespace(ch) || Character.isISOControl(ch))
        {
            nametf.setEditable(true);
        }
        else
        {
            nametf.setEditable(false);
        }
        
    }//GEN-LAST:event_nametfKeyPressed

    private void fnametfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fnametfKeyPressed
       
        char ch=evt.getKeyChar();
        
        if(Character.isLetter(ch) || Character.isWhitespace(ch) || Character.isISOControl(ch))
        {
            fnametf.setEditable(true);
        }
        else
        {
            fnametf.setEditable(false);
        }
                
    }//GEN-LAST:event_fnametfKeyPressed

    private void countrytfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_countrytfKeyPressed
        
        char ch=evt.getKeyChar();
        
        if(Character.isLetter(ch) || Character.isWhitespace(ch) || Character.isISOControl(ch))
        {
            countrytf.setEditable(true);
        }
        else
        {
            countrytf.setEditable(false);
        }
        
    }//GEN-LAST:event_countrytfKeyPressed

    private void provincetfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_provincetfKeyPressed
        
        char ch=evt.getKeyChar();
        
        if(Character.isLetter(ch) || Character.isWhitespace(ch) || Character.isISOControl(ch))
        {
            provincetf.setEditable(true);
        }
        else
        {
            provincetf.setEditable(false);
        }
        
    }//GEN-LAST:event_provincetfKeyPressed

    private void districttfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_districttfKeyPressed
        
        char ch=evt.getKeyChar();
        
        if(Character.isLetter(ch) || Character.isWhitespace(ch) || Character.isISOControl(ch))
        {
            districttf.setEditable(true);
        }
        else
        {
            districttf.setEditable(false);
        }
        
    }//GEN-LAST:event_districttfKeyPressed

    private void addresstfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addresstfKeyPressed
        
        char ch=evt.getKeyChar();
        
        if(Character.isLetter(ch) || Character.isWhitespace(ch) || Character.isISOControl(ch))
        {
            addresstf.setEditable(true);
        }
        else
        {
            addresstf.setEditable(false);
        }
        
    }//GEN-LAST:event_addresstfKeyPressed

    private void contacttfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contacttfKeyPressed
        
           char ch=evt.getKeyChar();
           
           if(Character.isDigit(ch) || Character.isWhitespace(ch) || Character.isISOControl(ch))
           {
               contacttf.setEditable(true);
           }
           else
           {
               contacttf.setEditable(false);
           }
        
    }//GEN-LAST:event_contacttfKeyPressed

    private void emergcontacttfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emergcontacttfKeyPressed
        
           char ch=evt.getKeyChar();
           
           if(Character.isDigit(ch) || Character.isWhitespace(ch) || Character.isISOControl(ch))
           {
               emergcontacttf.setEditable(true);
           }
           else
           {
               emergcontacttf.setEditable(false);
           }
        
    }//GEN-LAST:event_emergcontacttfKeyPressed

    private void rollnotfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rollnotfKeyPressed
        
            char ch=evt.getKeyChar();
            
           if(Character.isLetter(ch) || Character.isDigit(ch) || Character.isISOControl(ch))
           {
               rollnotf.setEditable(true);
           }
           else
           {
               rollnotf.setEditable(false);
           }
        
    }//GEN-LAST:event_rollnotfKeyPressed

    private void rollnotfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rollnotfFocusGained
        
        if(rollnotf.getText().equals("Roll No"))
        {
            rollnotf.setText("");
            rollnotf.setForeground(new Color(0,0,0));
        }
        
    }//GEN-LAST:event_rollnotfFocusGained

    private void rollnotfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rollnotfFocusLost
        
        if(rollnotf.getText().equals(""))
        {
            rollnotf.setText("Roll No");
            rollnotf.setForeground(new Color(153,153,153));
        }
        
    }//GEN-LAST:event_rollnotfFocusLost

    private void nametfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nametfFocusGained
        
        if(nametf.getText().equals("Name"))
        {
            nametf.setText("");
            nametf.setForeground(new Color(0,0,0));
        }
        
    }//GEN-LAST:event_nametfFocusGained

    private void nametfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nametfFocusLost
        
        if(nametf.getText().equals(""))
        {
            nametf.setText("Name");
            nametf.setForeground(new Color(153,153,153));
        }
        
    }//GEN-LAST:event_nametfFocusLost

    private void fnametfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fnametfFocusGained
        
        if(fnametf.getText().equals("Father Name"))
        {
            fnametf.setText("");
            fnametf.setForeground(new Color(0,0,0));
        }
        
    }//GEN-LAST:event_fnametfFocusGained

    private void fnametfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fnametfFocusLost
        
        if(fnametf.getText().equals(""))
        {
            fnametf.setText("Father Name");
            fnametf.setForeground(new Color(153,153,153));
        }
        
    }//GEN-LAST:event_fnametfFocusLost

    private void contacttfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contacttfFocusGained
        
        if(contacttf.getText().equals("03*********"))
        {
            contacttf.setText("");
            contacttf.setForeground(new Color(0,0,0));
        }
        
    }//GEN-LAST:event_contacttfFocusGained

    private void contacttfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contacttfFocusLost
        
        if(contacttf.getText().equals(""))
        {
            contacttf.setText("03*********");
            contacttf.setForeground(new Color(153,153,153));
        }
        
    }//GEN-LAST:event_contacttfFocusLost

    private void countrytfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_countrytfFocusGained
        
        if(countrytf.getText().equals("Country Name"))
        {
            countrytf.setText("");
            countrytf.setForeground(new Color(0,0,0));
        }
        
    }//GEN-LAST:event_countrytfFocusGained

    private void countrytfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_countrytfFocusLost
        
        if(countrytf.getText().equals(""))
        {
            countrytf.setText("Country Name");
            countrytf.setForeground(new Color(153,153,153));
        }
        
    }//GEN-LAST:event_countrytfFocusLost

    private void provincetfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_provincetfFocusGained
        
        if(provincetf.getText().equals("Province Name"))
        {
            provincetf.setText("");
            provincetf.setForeground(new Color(0,0,0));
        }
        
    }//GEN-LAST:event_provincetfFocusGained

    private void provincetfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_provincetfFocusLost
        
        if(provincetf.getText().equals(""))
        {
            provincetf.setText("Province Name");
            provincetf.setForeground(new Color(153,153,153));
        }
        
    }//GEN-LAST:event_provincetfFocusLost

    private void districttfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_districttfFocusGained
        
        if(districttf.getText().equals("District Name"))
        {
            districttf.setText("");
            districttf.setForeground(new Color(0,0,0));
        }
        
    }//GEN-LAST:event_districttfFocusGained

    private void districttfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_districttfFocusLost
        
        if(districttf.getText().equals(""))
        {
            districttf.setText("District Name");
            districttf.setForeground(new Color(153,153,153));
        }
        
    }//GEN-LAST:event_districttfFocusLost

    private void addresstfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addresstfFocusGained
        
        if(addresstf.getText().equals("Address"))
        {
            addresstf.setText("");
            addresstf.setForeground(new Color(0,0,0));
        }
        
    }//GEN-LAST:event_addresstfFocusGained

    private void addresstfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addresstfFocusLost
        
        if(addresstf.getText().equals(""))
        {
            addresstf.setText("Address");
            addresstf.setForeground(new Color(153,153,153));
        }
        
    }//GEN-LAST:event_addresstfFocusLost

    private void emailtfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailtfFocusGained
        
        if(emailtf.getText().equals("Email"))
        {
            emailtf.setText("");
            emailtf.setForeground(new Color(0,0,0));
        }
        
    }//GEN-LAST:event_emailtfFocusGained

    private void emailtfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailtfFocusLost
        
        if(emailtf.getText().equals(""))
        {
            emailtf.setText("Email");
            emailtf.setForeground(new Color(153,153,153));
        }
        
    }//GEN-LAST:event_emailtfFocusLost

    private void emergcontacttfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emergcontacttfFocusGained
        
        if(emergcontacttf.getText().equals("03*********"))
        {
            emergcontacttf.setText("");
            emergcontacttf.setForeground(new Color(0,0,0));
        }
        
    }//GEN-LAST:event_emergcontacttfFocusGained

    private void emergcontacttfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emergcontacttfFocusLost
        
        if(emergcontacttf.getText().equals(""))
        {
            emergcontacttf.setText("03*********");
            emergcontacttf.setForeground(new Color(153,153,153));
        }
        
    }//GEN-LAST:event_emergcontacttfFocusLost

    private void contacttfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contacttfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contacttfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StdDataCollectionNonAC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StdDataCollectionNonAC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StdDataCollectionNonAC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StdDataCollectionNonAC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StdDataCollectionNonAC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel address;
    private javax.swing.JTextField addresstf;
    private javax.swing.JLabel back;
    private javax.swing.JComboBox<String> bg;
    private javax.swing.JLabel bloodgroup;
    private javax.swing.JButton clear;
    private javax.swing.JLabel contact;
    private javax.swing.JTextField contacttf;
    private javax.swing.JLabel country;
    private javax.swing.JTextField countrytf;
    private javax.swing.JLabel district;
    private javax.swing.JTextField districttf;
    private javax.swing.JLabel email;
    private javax.swing.JTextField emailtf;
    private javax.swing.JLabel emergcontact;
    private javax.swing.JTextField emergcontacttf;
    private javax.swing.JLabel fname;
    private javax.swing.JTextField fnametf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel name;
    private javax.swing.JTextField nametf;
    private javax.swing.JLabel province;
    private javax.swing.JTextField provincetf;
    private javax.swing.JLabel rollno;
    private javax.swing.JTextField rollnotf;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
