/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DBSProject;

import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author Admin
 */
public class UserFrame extends javax.swing.JFrame {
    
    String rollno;
    
    /**
     * Creates new form UserFrame
     */
    public UserFrame() {
        initComponents();
        setSize(1200,700);
        setLocationRelativeTo(null);
        setResizable(false);
    }
    
    public void setRollNo(String rollno){
        
        this.rollno = rollno;
        
    }
    
    public String getRollNo(){
        
        return rollno;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        whichroom = new javax.swing.JLabel();
        userframepanel = new javax.swing.JPanel();
        welcome = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        acroombtn = new javax.swing.JButton();
        noacroom = new javax.swing.JButton();
        roomno = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(200, 100, 600, 600));
        getContentPane().setLayout(null);

        whichroom.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        whichroom.setText("Which type of room do you want?");
        getContentPane().add(whichroom);
        whichroom.setBounds(140, 180, 290, 30);

        userframepanel.setBackground(new java.awt.Color(248, 245, 241));
        userframepanel.setLayout(null);

        welcome.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        welcome.setText("Welcome To APNA Hostel");
        userframepanel.add(welcome);
        welcome.setBounds(310, 10, 590, 80);

        back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        userframepanel.add(back);
        back.setBounds(10, 10, 30, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/userframe.jpg"))); // NOI18N
        userframepanel.add(jLabel2);
        jLabel2.setBounds(510, 160, 650, 450);

        acroombtn.setBackground(new java.awt.Color(153, 204, 255));
        acroombtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        acroombtn.setText("AC Room");
        acroombtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        acroombtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acroombtnActionPerformed(evt);
            }
        });
        userframepanel.add(acroombtn);
        acroombtn.setBounds(140, 240, 210, 30);

        noacroom.setBackground(new java.awt.Color(153, 204, 255));
        noacroom.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        noacroom.setText("Non AC Room");
        noacroom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        noacroom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noacroomActionPerformed(evt);
            }
        });
        userframepanel.add(noacroom);
        noacroom.setBounds(140, 330, 210, 30);

        roomno.setBackground(new java.awt.Color(153, 204, 255));
        roomno.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        roomno.setText("See Your Room No");
        roomno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        roomno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomnoActionPerformed(evt);
            }
        });
        userframepanel.add(roomno);
        roomno.setBounds(140, 420, 210, 30);

        getContentPane().add(userframepanel);
        userframepanel.setBounds(0, 0, 1190, 670);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void acroombtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acroombtnActionPerformed
        
        boolean check = false;
        
        try{
            Connection con = new DBConnection().getConnection();
            Statement s = con.createStatement();
            ResultSet rs = s.executeQuery("select roll_no from hostel_data_ac");
            while(rs.next())
            {
                if(rs.getString("roll_no").equals(getRollNo()))
                {
                    check = true;
                    break;
                }
            }
            
            if(check)
            {
                JOptionPane.showMessageDialog(null, "You have already allocated room, To know your room no press \"see your room no\".");
            }
            
            else
            {
                ResultSet rs2 = s.executeQuery("select roll_no from hostel_data_non_ac");
                while(rs2.next())
                {
                    if(rs2.getString("roll_no").equals(getRollNo()))
                    {
                        check = true;
                        break;
                    }
                }
                
                if(check)
                {
                    JOptionPane.showMessageDialog(null, "You have already allocated room, To know your room no press \"see your room no\".");
                }
                
                else
                {
                    StdDataCollectionAC obj = new StdDataCollectionAC();
                    obj.setRollNo(getRollNo());
                    obj.setVisible(true);
                    this.dispose();
                }
            }   
            con.close();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_acroombtnActionPerformed

    private void noacroomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noacroomActionPerformed
        
        boolean check = false;
        
        try{
            Connection con = new DBConnection().getConnection();
            Statement s = con.createStatement();
            ResultSet rs = s.executeQuery("select roll_no from hostel_data_non_ac");
            while(rs.next())
            {
                if(rs.getString("roll_no").equals(getRollNo()))
                {
                    check = true;
                    break;
                }
            }
            
            if(check)
            {
                JOptionPane.showMessageDialog(null, "You have already allocated room, To know your room no press \"see room no\".");
            }
            
            else
            {
                ResultSet rs2 = s.executeQuery("select roll_no from hostel_data_ac");
                while(rs2.next())
                {
                    if(rs2.getString("roll_no").equals(getRollNo()))
                    {
                        check = true;
                        break;
                    }
                }
                
                if(check)
                {
                    JOptionPane.showMessageDialog(null, "You have already allocated room, To know your room no press \"see room no\".");
                }
                
                else
                {
                    StdDataCollectionNonAC obj = new StdDataCollectionNonAC();
                    obj.setRollNo(getRollNo());
                    obj.setVisible(true);
                    this.dispose();
                }
            }   
            con.close();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_noacroomActionPerformed

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        
        new SignUp().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_backMouseClicked

    private void roomnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomnoActionPerformed
        
        boolean check = false;
        String roomno=null;
        
        try{
            Connection con = new DBConnection().getConnection();
            Statement s = con.createStatement();
            ResultSet rs = s.executeQuery("select * from ac_rooms_allocation");
            while(rs.next())
            {
                if(rs.getString("std_1_roll_no").equals(getRollNo()))
                {
                    roomno = rs.getString("room_no");
                    check = true;
                    break;
                }
                
                else if(rs.getString("std_2_roll_no").equals(getRollNo()))
                {
                    roomno = rs.getString("room_no");
                    check = true;
                    break;
                }
            }
            
            if(check)
            {
                JOptionPane.showMessageDialog(null, "Your room no is "+roomno);
            }
            
            else
            {
                ResultSet rs2 = s.executeQuery("select * from non_ac_rooms_allocation");
                while(rs2.next())
                {
                    if(rs2.getString("std_1_roll_no").equals(getRollNo()))
                    {
                        roomno = rs2.getString("room_no");
                        check = true;
                        break;
                    }
                    
                    if(rs2.getString("std_2_roll_no").equals(getRollNo()))
                    {
                        roomno = rs2.getString("room_no");
                        check = true;
                        break;
                    }
                }
                
                if(check)
                {
                    JOptionPane.showMessageDialog(null, "Your room no is "+roomno);
                }
                
                else
                {
                    JOptionPane.showMessageDialog(null, "Your are not allocated any room.");
                }
            }
            con.close();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_roomnoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acroombtn;
    private javax.swing.JLabel back;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton noacroom;
    private javax.swing.JButton roomno;
    private javax.swing.JPanel userframepanel;
    private javax.swing.JLabel welcome;
    private javax.swing.JLabel whichroom;
    // End of variables declaration//GEN-END:variables
}
