/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DBSProject;

/**
 *
 * @author Admin
 */
public class UserFrame extends javax.swing.JFrame {
    
    /**
     * Creates new form UserFrame
     */
    public UserFrame() {
        initComponents();
        setSize(1200,700);
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        whichroom = new javax.swing.JLabel();
        userframepanel = new javax.swing.JPanel();
        welcome = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        acroombtn = new javax.swing.JButton();
        noacroom = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(200, 100, 600, 600));
        getContentPane().setLayout(null);

        whichroom.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        whichroom.setText("Which type of room do you want?");
        getContentPane().add(whichroom);
        whichroom.setBounds(140, 180, 290, 30);

        userframepanel.setBackground(new java.awt.Color(248, 245, 241));
        userframepanel.setLayout(null);

        welcome.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        welcome.setText("Welcome To APNA Hostel");
        userframepanel.add(welcome);
        welcome.setBounds(310, 10, 590, 80);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        userframepanel.add(jLabel1);
        jLabel1.setBounds(10, 10, 30, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/userframe.jpg"))); // NOI18N
        userframepanel.add(jLabel2);
        jLabel2.setBounds(510, 160, 650, 450);

        acroombtn.setBackground(new java.awt.Color(153, 204, 255));
        acroombtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        acroombtn.setText("AC Room");
        acroombtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        acroombtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acroombtnActionPerformed(evt);
            }
        });
        userframepanel.add(acroombtn);
        acroombtn.setBounds(140, 240, 210, 30);

        noacroom.setBackground(new java.awt.Color(153, 204, 255));
        noacroom.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        noacroom.setText("Non AC Room");
        noacroom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        noacroom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noacroomActionPerformed(evt);
            }
        });
        userframepanel.add(noacroom);
        noacroom.setBounds(140, 340, 210, 30);

        getContentPane().add(userframepanel);
        userframepanel.setBounds(0, 0, 1190, 670);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void acroombtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acroombtnActionPerformed
        
        new StdDataCollectionAC().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_acroombtnActionPerformed

    private void noacroomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noacroomActionPerformed
        
        new StdDataCollectionNonAC().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_noacroomActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        
        new SignUp().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acroombtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton noacroom;
    private javax.swing.JPanel userframepanel;
    private javax.swing.JLabel welcome;
    private javax.swing.JLabel whichroom;
    // End of variables declaration//GEN-END:variables
}
